
-- Migration: AI Clinical Reports System (Phase 2: The Brain)
-- Stores AI-generated progress reports and raw annotations for review.

-- 1. Create the Clinical Reports Table
CREATE TABLE IF NOT EXISTS public.clinical_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    therapist_id UUID NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    video_id TEXT, -- Optional: Link to Cloudinary video ID if relevant
    
    -- Structure of the input (What the Therapist saw)
    raw_annotations JSONB DEFAULT '[]'::jsonb, -- Array of {timestamp, note, type}
    
    -- The Output (The AI Report)
    content TEXT, -- Markdown format generated by Gemini
    
    -- Metadata
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Add Index for Performance
CREATE INDEX IF NOT EXISTS idx_clinical_reports_patient ON public.clinical_reports(patient_id);
CREATE INDEX IF NOT EXISTS idx_clinical_reports_therapist ON public.clinical_reports(therapist_id);

-- 3. Enable RLS
ALTER TABLE public.clinical_reports ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies

-- Policy: Therapists manage their own reports (Create, Read, Update, Delete)
CREATE POLICY "Therapists manage own reports"
ON public.clinical_reports
FOR ALL
USING (auth.uid() = therapist_id);

-- Policy: Parents can READ only PUBLISHED reports about themselves
CREATE POLICY "Parents view published reports"
ON public.clinical_reports
FOR SELECT
USING (
    auth.uid() = patient_id 
    AND status = 'published'
);

NOTIFY pgrst, 'reload schema';
