-- 1. Table to store the summary of a game session
CREATE TABLE IF NOT EXISTS game_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  game_type TEXT NOT NULL DEFAULT 'detail_spotter',
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  
  -- Core Scores
  final_score INTEGER,
  accuracy_percentage DECIMAL,
  avg_reaction_time_ms INTEGER,
  
  -- Scientific Metadata
  difficulty_level_reached INTEGER 
);

-- 2. Table for Raw Telemetry
CREATE TABLE IF NOT EXISTS assessment_telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES game_sessions(id) ON DELETE CASCADE,
  
  target_position_index INTEGER,
  click_position_index INTEGER,
  is_correct BOOLEAN,
  
  reaction_time_ms INTEGER,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE game_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_telemetry ENABLE ROW LEVEL SECURITY;

-- RLS Policies for game_sessions
CREATE POLICY "Users can view own game sessions"
ON game_sessions FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own game sessions"
ON game_sessions FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own game sessions"
ON game_sessions FOR UPDATE
USING (auth.uid() = user_id);

-- RLS Policies for assessment_telemetry (via session ownership)
CREATE POLICY "Users can view own telemetry"
ON assessment_telemetry FOR SELECT
USING (EXISTS (
  SELECT 1 FROM game_sessions 
  WHERE game_sessions.id = assessment_telemetry.session_id 
  AND game_sessions.user_id = auth.uid()
));

CREATE POLICY "Users can insert own telemetry"
ON assessment_telemetry FOR INSERT
WITH CHECK (EXISTS (
  SELECT 1 FROM game_sessions 
  WHERE game_sessions.id = assessment_telemetry.session_id 
  AND game_sessions.user_id = auth.uid()
));