// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Warn developers if environment variables are missing
if (!SUPABASE_URL || SUPABASE_URL === 'https://your-project-id.supabase.co') {
  console.warn(
    '⚠️ VITE_SUPABASE_URL is not configured!\n' +
    'Please update your .env file with your Supabase project URL.\n' +
    'Get it from: https://app.supabase.com/project/_/settings/api'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'your-anon-key-here') {
  console.warn(
    '⚠️ VITE_SUPABASE_ANON_KEY is not configured!\n' +
    'Please update your .env file with your Supabase anon key.\n' +
    'Get it from: https://app.supabase.com/project/_/settings/api'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});